version: '3'
services:
  odoo:
    image: odoo:16.0
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - data16:/var/lib/odoo
      - ./custom-addons:/mnt/extra-addons
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - db16:/var/lib/postgresql/data/pgdata

volumes:
  data16:
  db16:
